# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'src/docker-compose.yml'
    additionalDockerComposeFiles: '../ci/docker-compose.ci.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: '-p northwindstore up'
    arguments: '--build --force-recreate -d'
